name: 'DotCMS Commit Message Getter'
description: 'Gets the commit message for a given pull request or push'
author: 'Victor Alfaro'
inputs:
  excludeTitle:
    description: 'Setting this input to true will exclude the Pull Request title.'
    required: false
    default: 'true'
  excludeDescription:
    description: 'Setting this input to true will exclude the Pull Request description.'
    required: false
    default: 'true'
  checkAllCommitMessages:
    description: 'Setting this input to true will check all Pull Request commits'
    required: false
    default: 'true'
  latestCommitMessage:
    description: 'Setting this input to true will get latest commit message instead of all'
    required: false
    default: 'true'
  accessToken:
    description: 'you must provide GITHUB_TOKEN to this input if checkAllCommitMessages is true'
    required: false
runs:
  using: node12
  main: dist/index.js
branding:
  icon: 'check'
  color: 'blue'
